### ISSUE TITLE
problem with pushbutton.py

### ISSUE THREAD

**Issue by Enzoinventor** [shivasiddharth/GassistPi#166]
when I press the button, the assistant listens to me only once and then stops.
Or when he says what I can do for you? it does not emit the sound that comes back to listening and freezes again.
I tried to manually execute the pushbutton.py file and in the console the sentence I said and then stop appears.
Even premento ctrl + c does not exit the terminal.
I await your advice.
Thank you in advance

**Comment by shivasiddharth** [comment]
Will look into it

**Comment by shivasiddharth** [comment]
Can you replace the existing file with [this](https://github.com/shivasiddharth/GassistPi/blob/tasmota-wemo/src/pushbutton.py) and then check to see if the issue is fixed ?

**Comment by Enzoinventor** [comment]
hi is the same file I own.
I noticed that as soon as I turn on the raspberry, I hear the mp3 file hi !! and when I press the button and say hello, he answers and then hangs everything even hey google no longer works. I also noticed that when you stop the CPU goes to 0 while it should be between 20/30 max as usual.

**Comment by shivasiddharth** [comment]
Nope it's not the same file. It's from a Dev branch that I am currently working on.

**Comment by Enzoinventor** [comment]
ok, I replaced the file but the problem persists as before

**Comment by shivasiddharth** [comment]
ok, thanks

**Comment by shivasiddharth** [comment]
Ok, I have fixed that issue. replace your existing file with [this](https://github.com/shivasiddharth/GassistPi/blob/tasmota-wemo/src/pushbutton.py).

**Comment by Enzoinventor** [comment]
hi, i've replaced the file again but i get the same error.
At this point I reformat the sd and start from scratch in order to find the solution going for exclusion.
the file you edited is already inside Gassistpi, since I will have to recon the project?
thank you

**Comment by shivasiddharth** [comment]
I tested the moded file and the error seemed to have been fixed. like i said before, its from the development branch, so even if you clone it again, you would not get that file. You will need to manually download and replace.

**Comment by Enzoinventor** [comment]
hi, I've formatted and reinstalled everything but the problem persists.
can you show me how did you connect gpio22 as a trigger pin? because I noticed that the loop is still starting pushbutton.py.
thank you

**Comment by shivasiddharth** [comment]
I have already mentioned this a couple of times. Re-installing does not work. The fixed or modified script is still in the test branch, i have not merged it. You need to manually download and replace.

**Comment by Enzoinventor** [comment]
yes I know!!! I modified the file as you said before taking it from the branch
