### ISSUE TITLE
SyntaxError when starting manually

### ISSUE THREAD

**Issue by georgefst** [shivasiddharth/GassistPi#492]
I run:
`/home/pi/env/bin/python -u /home/pi/GassistPi/src/main.py --device_model_id 'replace this with the model id'
`
(with my model id, and quotes removed)

and get:
`File "/home/pi/GassistPi/src/main.py", line 223
    if event.type == EventType.ON_CONVERSATION_TURN_TIMEOUT or event.type == EventType.ON_NO_RESPONSE):
                                                                                                     ^
SyntaxError: invalid syntax
`

**Comment by shivasiddharth** [comment]
Fixed.

**Comment by LorenzoJenneker** [comment]
Still not working for me :'( please assist. I have the exact same error. At some point the start-up tone kept repeating in about 1mim intervals (don't know if it's related). Also "Ok google" does not work. Simply no response. No errors occurred at any point except as above. PLEASE PLEASE PLEASE assist :'( :'(
